#! /bin/bash

cd Filter_1_eExp_RelErr_mid_seg
./CLEAN;
cd ../Filter_2_eExp_AbsErr_mid_seg
./CLEAN;
cd ../Filter_3_eLin_RelErr_mid_seg
./CLEAN;
cd ../Filter_4_eLin_AbsErr_mid_seg
./CLEAN;
cd ../"Filter_5_Complex_Type 2049 pt"
./CLEAN;
cd ../"Filter_6_Complex_Type 1024 pt"
./CLEAN;
cd ..

